source:
  photometric_band: R+I
  zenith:
    value: [8,8,8]
    units: arcmin
  azimuth:
    value: [0,120,240]
    units: degree
  magnitude: [0,0,0]
  rays_box_size: 25.5000
  rays_box_sampling: 769 # N_SIDE_LENSLET*16+1 (16 pixel per lenslet)
  rays_origin: [0,0,25]
sensor:
  class: GeometricShackHartmann
  args:
    N_SIDE_LENSLET: 48 
    d: 0.53125 # [meter], rays_box_size/N_SIDE_LENSLET
    N_GS: 3
    intensityThreshold: 0.5
  calibrate_args:
    threshold: 0.5
interaction matrices: 
  calibrations:
    M12_RBM:
      method_id: AGWS_calibrate
      args:
        coupled: true
        filterMirrorRotation: false
        stroke: [1.0e-6,1.0e-6,1.0e-6,1.0e-6,1.0e-6]
        fluxThreshold: 0.5
        includeBM: false
  pseudo_inverse:
    n_threshold: [12]
    insert_zeros: [[41,82]]
  filename: AGWS_coupled_rotfilt
